### ISSUE TITLE
can any one explain , how he is created block - code in below   

### ISSUE THREAD

**Issue by Danyal-sys** [CaviarChen/CubicTetris#2]
public class General : MonoBehaviour {

    // structure for block data
    public struct Block {
	    public int[,,] block;
	    public int size;
    }

    public static readonly float cubeSize = 1.05f;
	// width is always 2
	public static readonly int width = 6;
    public static readonly int length = 8;
    public static readonly int height = 10;

    public static readonly float timeForEachDrop = 1.5f;
    public static readonly float timeForEachMoveAni = 0.2f;
    // degree per second
    public static readonly float rotateSpeed = 720.0f;  

    // takes x in [0,1] and return y in [0,1]
    // (-cos(x*pi)+1) / 2
    // makes moving smooth
    public static float rubberBandFunction(float x) {
        return (-Mathf.Cos(x * Mathf.PI) + 1) / 2.0f;
    }

    // preset blocks
    public static Block[] generateBlockTemplate() {
            
        General.Block[] blocks = new General.Block[12];
        blocks[0].block = new int[2, 4, 4] {
        {
            {0, 0, 0, 0},
            {0, 1, 0, 0},
            {0, 0, 0, 0},
            {0, 0, 0, 0},
        },
        {
            {0, 0, 0, 0},
            {2, 3, 4, 0},
            {0, 0, 0, 0},
            {0, 0, 0, 0}
        }
		};
        // size decide the center of the block (for rotating)
        blocks[0].size = 3;

        blocks[1].block = new int[2, 4, 4] {
        {
            {0, 1, 0, 0},
            {2, 3, 4, 0},
            {0, 0, 0, 0},
            {0, 0, 0, 0},
        },
        {
            {0, 0, 0, 0},
            {0, 0, 0, 0},
            {0, 0, 0, 0},
            {0, 0, 0, 0},

        }
        };

        blocks[1].size = 3;

		blocks[2].block = new int[2, 4, 4] {
		{
			{0, 1, 2, 0},
			{0, 3, 0, 0},
			{0, 4, 0, 0},
			{0, 0, 0, 0},
		},
		{
			{0, 0, 0, 0},
			{0, 0, 0, 0},
			{0, 0, 0, 0},
			{0, 0, 0, 0},
		}
		};

		blocks[2].size = 4;

		blocks[3].block = new int[2, 4, 4] {
		{
			{0, 1, 2, 0},
			{0, 0, 3, 0},
			{0, 0, 4, 0},
			{0, 0, 0, 0},
		},
		{
			{0, 0, 0, 0},
			{0, 0, 0, 0},
			{0, 0, 0, 0},
			{0, 0, 0, 0},
		}
		};

		blocks[3].size = 4;

		blocks[4].block = new int[2, 4, 4] {
		{
			{0, 1, 0, 0},
			{0, 2, 0, 0},
			{0, 3, 0, 0},
			{0, 0, 0, 0},
		},
		{
			{0, 4, 0, 0},
			{0, 0, 0, 0},
			{0, 0, 0, 0},
			{0, 0, 0, 0},
		}
		};

		blocks[4].size = 3;

		blocks[5].block = new int[2, 4, 4] {
		{
			{0, 1, 0, 0},
			{0, 0, 0, 0},
			{0, 0, 0, 0},
			{0, 0, 0, 0},
		},
		{
			{0, 2, 0, 0},
			{0, 3, 0, 0},
			{0, 4, 0, 0},
			{0, 0, 0, 0},
		}
		};

		blocks[5].size = 3;

		blocks[6].block = new int[2, 4, 4] {
		{
			{0, 1, 0, 0},
			{0, 2, 0, 0},
			{0, 3, 0, 0},
			{0, 4, 0, 0},
		},
		{
			{0, 0, 0, 0},
			{0, 0, 0, 0},
			{0, 0, 0, 0},
			{0, 0, 0, 0},
		}
		};

		blocks[6].size = 4;

		blocks[7].block = new int[2, 4, 4] {
			{
				{0, 0, 0, 0},
				{0, 1, 2, 0},
				{3, 4, 0, 0},
				{0, 0, 0, 0},
			},
			{
				{0, 0, 0, 0},
				{0, 0, 0, 0},
				{0, 0, 0, 0},
				{0, 0, 0, 0},
			}
		};

		blocks[7].size = 3;

		blocks[8].block = new int[2, 4, 4] {
			{
				{0, 0, 0, 0},
				{1, 2, 0, 0},
				{0, 3, 4, 0},
				{0, 0, 0, 0},
			},
			{
				{0, 0, 0, 0},
				{0, 0, 0, 0},
				{0, 0, 0, 0},
				{0, 0, 0, 0},
			}
		};

		blocks[8].size = 3;

		blocks[9].block = new int[2, 4, 4] {
			{
				{0, 1, 0, 0},
				{0, 2, 0, 0},
				{0, 0, 0, 0},
				{0, 0, 0, 0},
			},
			{
				{0, 3, 0, 0},
				{0, 4, 0, 0},
				{0, 0, 0, 0},
				{0, 0, 0, 0},
			}
		};

		blocks[9].size = 3;

        blocks[10].block = new int[2, 4, 4] {
            {
                {1, 2, 0, 0},
                {3, 4, 0, 0},
                {0, 0, 0, 0},
                {0, 0, 0, 0},
            },
            {
                {0, 0, 0, 0},
                {0, 0, 0, 0},
                {0, 0, 0, 0},
                {0, 0, 0, 0},
            }
        };

        blocks[10].size = 2;

		blocks[11].block = new int[2, 4, 4] {
			{
				{0, 0, 0, 0},
				{0, 1, 0, 0},
				{0, 0, 0, 0},
				{0, 0, 0, 0},
			},
			{
				{0, 0, 0, 0},
				{0, 0, 0, 0},
				{0, 0, 0, 0},
				{0, 0, 0, 0},
			}
		};

		blocks[11].size = 3;

        return blocks;
    }

**Comment by CaviarChen** [comment]
To be honest, looking at code that I wrote 3 years ago is definitely not a good experience. Especially the code quality of CubicTetris is pretty bad (The format of the code you posted is a mess).

I am not sure what specific part you are asking. In general, this part hard coded all blocks in the game.

<img width="107" alt="block" src="https://user-images.githubusercontent.com/8278409/80698015-6f378780-8b0c-11ea-9d66-6a7202f74bd7.png">

For eample, this one is defined by the following code.
```
 blocks[1].block = new int[2, 4, 4] {
    {
        {0, 1, 0, 0},
        {2, 3, 4, 0},
        {0, 0, 0, 0},
        {0, 0, 0, 0},
    },
    {
        {0, 0, 0, 0},
        {0, 0, 0, 0},
        {0, 0, 0, 0},
        {0, 0, 0, 0},

    }
    };
    blocks[1].size = 3;
```
The 2x4x4 array is describing the shape of it where 0 means nothing and >0 is for a single "cube" in this thing.
It seams each "cube" should have a distinct id starting from 1. I can't remeber why but it's definitely for simplify some computations later on.
<img width="107" alt="block" src="https://user-images.githubusercontent.com/8278409/80698677-685d4480-8b0d-11ea-9058-2fef61802136.png">

As for` size = 3`, it's used for determining the center of this shape. In this case we consider this thing is 3x3 and the center is at the "cube" 3.

**Comment by Danyal-sys** [comment]
i figure it out my own , i just change all your code lol , btw thanks for reply
